### ISSUE TITLE
Deprecations for TerriaJS v8.0.0

### ISSUE THREAD

**Issue by tephenavies** [TerriaJS/terriajs#4212]
Things that will no longer be supported in version 8:
- WMS region mapping
    * Replaced by vector tile region mapping
- `AbsIttCatalogGroup` and `AbsIttCatalogItem`
    * Replaced with SDMX JSON
- IE11?
- GNAF geocoding
- CSV batch geocoding

We'll add to this list as we come across other things we plan to deprecate.

These deprecations will be documented in upcoming releases of TerriaJS v7.
To document them.

**Comment by rowanwins** [comment]
Potentially I'd like to suggest we deprecate the following catalog types. 
`AbsIttCatalogGroup` and `AbsIttCatalogItem`

These were purpose built to integrate with ABS data. I'm hoping they can be replaced by the `SdmxCatalogItem` which is an actual standard for this stuff. Myself & Ana are meeting with ABS on 4th Aug so I'll raise it then.

**Comment by tephenavies** [comment]
Done in:

* #5712 
* #5728

**Comment by irbian** [comment]
I have read between the issues but I still don't haven found why "WMS region mapping" is deprecated

any light on that?
