### ISSUE TITLE
Story share URL regression forcing return to first scene

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#5301]
If you create a multi-scene story and generate a share URL for the story and you want it to start at anything but the first scene you no longer can, when the story loads it always returns to the first scene. We previously allowed indexing a particular non-first scene in stories.

Here is a story with 3 scenes, where we have created the share URL when we are at Scene 2: https://qld.digitaltwin.terria.io/#share=s-pST7P4oUkxxKJPofmEiUChaLFUR

Note how when you initially load the map the scene that is loaded behind the modals is viewing the horizon, this is Scene 2:

<img width="1185" alt="Screen Shot 2021-03-04 at 3 57 46 pm" src="https://user-images.githubusercontent.com/5283003/109913581-5f776980-7d02-11eb-8991-56346b7d1713.png">

However, when you say Yes you are immediately sent to Scene 1:

<img width="1185" alt="Screen Shot 2021-03-04 at 3 59 22 pm" src="https://user-images.githubusercontent.com/5283003/109913729-977eac80-7d02-11eb-9d81-472c6b213f16.png">

That's a bug. We want to remain on Scene 2, like I've mocked up here (but since I haven't closed the intro modal that should still be there):

<img width="1185" alt="Screen Shot 2021-03-04 at 4 00 05 pm" src="https://user-images.githubusercontent.com/5283003/109913792-b1b88a80-7d02-11eb-82aa-e56eb151a3dc.png">

**Comment by AnaBelgun** [comment]
This bug would affect the pedestrian - story modes interaction too.

**Comment by AnaBelgun** [comment]
I think this is fixed?

**Comment by meh9** [comment]
No not fixed yet, still the same behaviour on latest `next` build.
