### ISSUE TITLE
Scrolling of disclaimer / welcome panel on iPhone broken

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#6525]
Currently when users are trying to scroll the text on a landing page disclaimer in iPhone it doesn't work and it prevents them to access the application. 
To test:
- open https://map.geo-rapp.org/ on iPhone 
- Try to scroll the disclaimer page (blocked) 
- use Chrome and Safari

**Comment by AnaBelgun** [comment]
Fixed by https://github.com/TerriaJS/terriajs/pull/6535

**Comment by KerriG1** [comment]
![IoS disclaimer scroll issue](https://user-images.githubusercontent.com/92421123/190538991-88ebcff6-b7bc-4963-aa80-1ddd56b911df.png)

Hi @AnaBelgun unfortunately, my iphone is still experiencing this issue. Image to support this is attached.

kerri

**Comment by AnaBelgun** [comment]
hi @KerriG1 this issue is indeed about the scrolling but affecting a different app which was not deployed yet with the fix. 
Please let us know if the scrolling is still an issue on DTV; Geoglam (map.geo-rapp.org) will be deployed next week but that doesn't affect DTV.

**Comment by KerriG1** [comment]
@AnaBelgun Hey Ana - this definitely can be passed because the disclaimer on DTV is not long enough to need scrolling. The agree button is on the page with the disclaimer so scrolling is not required. If it does get any longer in the future, it will be impacted. So a happy pass :-)
